### ISSUE TITLE
Noise Suppression Properly Verify

### ISSUE THREAD

**Issue by dack-fe** [fpga-open-speech-tools/simulink_models#70]
The Noise Suppression model contains additional scripts - https://github.com/fpga-open-speech-tools/simulink_models/tree/dev/models/noise_suppression/MATLAB_scripts

What are these scripts? Can they be removed?

**Comment by tvannoy** [comment]
They were during development and testing. Essentially, the algorithm was implemented in MATLAB first, then implemented in Simulink. 

They can be removed. They could perhaps be incorporated into `verifySim`; the output of [adaptiveWienerFilt.m](https://github.com/fpga-open-speech-tools/simulink_models/blob/dev/models/noise_suppression/MATLAB_scripts/adaptiveWienerFilt.m) should be close to the output of the Simulink model, but I don't believe it was ever rigorously verified.

**Comment by fe-wickham** [comment]
I think it would be worth it to get the scripts used in `verifySim` as ideally we can show in our example projects actual verification going on. If any of the scripts end up not being needed for verification we can get rid of them then

**Comment by tvannoy** [comment]
Agreed. This would be a good example of a non-trivial verification, versus something trivial like the simple gain. `adaptiveWienerFilt` should be the only file needed for verification. 

We can either keep `adaptiveWienerFilt` as a separate file or put the functions into `verifySim` as local functions. Do we have a preference here?

**Comment by fe-wickham** [comment]
Personally I am preferential to keeping something as complicated as `adaptiveWienerFilt` as a separate file just to keep the `verifySim` file still easy and quick to parse for readers rather than getting bogged down in the details if they aren't interested.   

Its also a bit better practice as it enables to us to do more complex validation when it is used as part of a bigger model, ie the ANM components and validating the larger and larger sections of it.

I have updated this issue's title to reflect that the verification should be updated
